import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';

import 'release_config_guard.dart';

// A direct Flutter release build must fail closed at compile time. The guarded
// release command supplies both defines; without them this constant assertion
// fails and the Dart compiler rejects the build.
class _ReleaseModeCompileTimeGuard {
  const _ReleaseModeCompileTimeGuard()
    : assert(
        !kReleaseMode ||
            (const bool.fromEnvironment('OCEANEYES_PRODUCTION') &&
                const bool.fromEnvironment('OCEANEYES_RELEASE_GUARD')),
        'Customer release builds require the guarded production defines.',
      ),
      valid = true;

  final bool valid;
}

const _releaseModeCompileTimeGuard = _ReleaseModeCompileTimeGuard();

/// Build-time production settings.
///
/// Customer-release values are supplied with the private
/// `--dart-define-from-file` configuration; no environment-specific Firebase
/// configuration is committed to the repository. Native debug/emulator builds
/// may rely on the gitignored files generated by `flutterfire configure`, but
/// the guarded customer release still requires its validated Dart defines.
class OceanEyesProductionConfig {
  const OceanEyesProductionConfig({
    required this.enabled,
    required this.appCheckEnabled,
    required this.appCheckDebug,
    required this.recaptchaV3SiteKey,
    required this.functionsRegion,
    required this.useFirebaseEmulators,
    required this.firestoreEmulatorHost,
    required this.firestoreEmulatorPort,
    required this.authEmulatorHost,
    required this.authEmulatorPort,
    required this.functionsEmulatorHost,
    required this.functionsEmulatorPort,
    required this.apiKey,
    required this.projectId,
    required this.messagingSenderId,
    required this.androidAppId,
    required this.iosAppId,
    required this.webAppId,
    required this.authDomain,
    required this.storageBucket,
    required this.measurementId,
    required this.iosBundleId,
    required this.iosClientId,
    required this.androidClientId,
    required this.googleWebClientId,
    required this.webPushVapidKey,
    required this.buildName,
    required this.buildNumber,
    required this.privacyPolicyUrl,
    required this.termsOfServiceUrl,
  });

  factory OceanEyesProductionConfig.fromEnvironment() {
    return OceanEyesProductionConfig(
      // Release builds default to the production composition. This prevents a
      // missing define from silently selecting the fixture shell. The release
      // guard below still requires the explicit production define and all
      // target-specific values before startup can continue.
      enabled:
          const bool.fromEnvironment(
            'OCEANEYES_PRODUCTION',
            defaultValue: kReleaseMode,
          ) &&
          _releaseModeCompileTimeGuard.valid,
      appCheckEnabled: const bool.fromEnvironment(
        'OCEANEYES_APP_CHECK',
        defaultValue: true,
      ),
      appCheckDebug: const bool.fromEnvironment('OCEANEYES_APP_CHECK_DEBUG'),
      recaptchaV3SiteKey: const String.fromEnvironment(
        'OCEANEYES_RECAPTCHA_V3_SITE_KEY',
      ),
      functionsRegion: const String.fromEnvironment(
        'OCEANEYES_FUNCTIONS_REGION',
        defaultValue: 'us-central1',
      ),
      useFirebaseEmulators: const bool.fromEnvironment(
        'OCEANEYES_FIREBASE_EMULATORS',
      ),
      firestoreEmulatorHost: const String.fromEnvironment(
        'OCEANEYES_FIRESTORE_EMULATOR_HOST',
        defaultValue: 'localhost',
      ),
      firestoreEmulatorPort: const int.fromEnvironment(
        'OCEANEYES_FIRESTORE_EMULATOR_PORT',
        defaultValue: 8080,
      ),
      authEmulatorHost: const String.fromEnvironment(
        'OCEANEYES_AUTH_EMULATOR_HOST',
        defaultValue: 'localhost',
      ),
      authEmulatorPort: const int.fromEnvironment(
        'OCEANEYES_AUTH_EMULATOR_PORT',
        defaultValue: 9099,
      ),
      functionsEmulatorHost: const String.fromEnvironment(
        'OCEANEYES_FUNCTIONS_EMULATOR_HOST',
        defaultValue: 'localhost',
      ),
      functionsEmulatorPort: const int.fromEnvironment(
        'OCEANEYES_FUNCTIONS_EMULATOR_PORT',
        defaultValue: 5001,
      ),
      apiKey: const String.fromEnvironment('OCEANEYES_FIREBASE_API_KEY'),
      projectId: const String.fromEnvironment('OCEANEYES_FIREBASE_PROJECT_ID'),
      messagingSenderId: const String.fromEnvironment(
        'OCEANEYES_FIREBASE_MESSAGING_SENDER_ID',
      ),
      androidAppId: const String.fromEnvironment(
        'OCEANEYES_FIREBASE_ANDROID_APP_ID',
      ),
      iosAppId: const String.fromEnvironment('OCEANEYES_FIREBASE_IOS_APP_ID'),
      webAppId: const String.fromEnvironment('OCEANEYES_FIREBASE_WEB_APP_ID'),
      authDomain: const String.fromEnvironment(
        'OCEANEYES_FIREBASE_AUTH_DOMAIN',
      ),
      storageBucket: const String.fromEnvironment(
        'OCEANEYES_FIREBASE_STORAGE_BUCKET',
      ),
      measurementId: const String.fromEnvironment(
        'OCEANEYES_FIREBASE_MEASUREMENT_ID',
      ),
      iosBundleId: const String.fromEnvironment(
        'OCEANEYES_FIREBASE_IOS_BUNDLE_ID',
        defaultValue: 'com.oceaneyes.oceaneyes',
      ),
      iosClientId: const String.fromEnvironment(
        'OCEANEYES_FIREBASE_IOS_CLIENT_ID',
      ),
      androidClientId: const String.fromEnvironment(
        'OCEANEYES_FIREBASE_ANDROID_CLIENT_ID',
      ),
      googleWebClientId: const String.fromEnvironment(
        'OCEANEYES_GOOGLE_WEB_CLIENT_ID',
      ),
      webPushVapidKey: const String.fromEnvironment(
        'OCEANEYES_FIREBASE_WEB_PUSH_VAPID_KEY',
      ),
      buildName: const String.fromEnvironment('OCEANEYES_BUILD_NAME'),
      buildNumber: const String.fromEnvironment('OCEANEYES_BUILD_NUMBER'),
      privacyPolicyUrl: const String.fromEnvironment(
        'OCEANEYES_PRIVACY_POLICY_URL',
      ),
      termsOfServiceUrl: const String.fromEnvironment(
        'OCEANEYES_TERMS_OF_SERVICE_URL',
      ),
    );
  }

  final bool enabled;
  final bool appCheckEnabled;
  final bool appCheckDebug;
  final String recaptchaV3SiteKey;
  final String functionsRegion;
  final bool useFirebaseEmulators;
  final String firestoreEmulatorHost;
  final int firestoreEmulatorPort;
  final String authEmulatorHost;
  final int authEmulatorPort;
  final String functionsEmulatorHost;
  final int functionsEmulatorPort;

  final String apiKey;
  final String projectId;
  final String messagingSenderId;
  final String androidAppId;
  final String iosAppId;
  final String webAppId;
  final String authDomain;
  final String storageBucket;
  final String measurementId;
  final String iosBundleId;
  final String iosClientId;
  final String androidClientId;
  final String googleWebClientId;
  final String webPushVapidKey;
  final String buildName;
  final String buildNumber;
  final String privacyPolicyUrl;
  final String termsOfServiceUrl;

  /// Set only by the guarded release build command/CI job.
  static const bool releaseArtifactGuardPresent = bool.fromEnvironment(
    'OCEANEYES_RELEASE_GUARD',
  );
  static const String productionDefineValue = String.fromEnvironment(
    'OCEANEYES_PRODUCTION',
  );

  bool get hasDartDefinedFirebaseOptions =>
      _isConfigured(apiKey) &&
      _isConfigured(projectId) &&
      _isConfigured(messagingSenderId) &&
      _isConfigured(_appIdForCurrentPlatform);

  /// Returns null on native platforms when setup should be loaded from the
  /// generated Google service file. Web always requires explicit options.
  FirebaseOptions? firebaseOptionsForCurrentPlatform() {
    if (!hasDartDefinedFirebaseOptions) return null;
    return FirebaseOptions(
      apiKey: apiKey,
      appId: _appIdForCurrentPlatform,
      messagingSenderId: messagingSenderId,
      projectId: projectId,
      authDomain: authDomain.isEmpty ? null : authDomain,
      storageBucket: storageBucket.isEmpty ? null : storageBucket,
      measurementId: measurementId.isEmpty ? null : measurementId,
      iosBundleId: defaultTargetPlatform == TargetPlatform.iOS
          ? iosBundleId
          : null,
      iosClientId: defaultTargetPlatform == TargetPlatform.iOS
          ? (iosClientId.isEmpty ? null : iosClientId)
          : null,
      androidClientId: defaultTargetPlatform == TargetPlatform.android
          ? (androidClientId.isEmpty ? null : androidClientId)
          : null,
    );
  }

  String get _appIdForCurrentPlatform {
    if (kIsWeb) return webAppId;
    return switch (defaultTargetPlatform) {
      TargetPlatform.android => androidAppId,
      TargetPlatform.iOS => iosAppId,
      _ => '',
    };
  }

  /// A user-facing configuration problem, or null when startup can proceed.
  String? validate() {
    if (kReleaseMode) {
      if (productionDefineValue.isEmpty) {
        return 'Customer release artifacts require an explicit '
            'OCEANEYES_PRODUCTION=true define; fixture mode is not allowed.';
      }
      if (!enabled) {
        return 'Customer release artifacts require '
            'OCEANEYES_PRODUCTION=true; fixture mode is not allowed.';
      }
      if (!releaseArtifactGuardPresent) {
        return 'This release was not built by the guarded release command. '
            'Run tool/build_release.dart with the private production file.';
      }
    }
    if (!enabled) return null;
    if (!kIsWeb &&
        defaultTargetPlatform != TargetPlatform.android &&
        defaultTargetPlatform != TargetPlatform.iOS) {
      return 'Production Google authentication is supported on Android, iOS, '
          'and web. Run this app with "-d chrome" for browser testing.';
    }
    if (kIsWeb && !hasDartDefinedFirebaseOptions) {
      return 'Flutter web requires real Firebase dart-defines; the current '
          'configuration is missing values or still contains placeholders.';
    }
    if (kIsWeb && !_isConfigured(googleWebClientId)) {
      return 'Web Google sign-in requires a real '
          'OCEANEYES_GOOGLE_WEB_CLIENT_ID.';
    }
    if (kIsWeb && appCheckEnabled && !_isConfigured(recaptchaV3SiteKey)) {
      return 'Web App Check requires a real '
          'OCEANEYES_RECAPTCHA_V3_SITE_KEY.';
    }
    if (functionsRegion.trim().isEmpty) {
      return 'OCEANEYES_FUNCTIONS_REGION cannot be empty.';
    }
    if (!kReleaseMode) return null;
    final releaseErrors = OceanEyesReleaseConfigGuard.validate(
      _dartDefines,
      target: _releaseTarget,
    );
    if (releaseErrors.isEmpty) return null;
    return 'Customer release configuration is invalid:\n'
        '${releaseErrors.map((error) => '- $error').join('\n')}';
  }

  OceanEyesReleaseTarget get _releaseTarget {
    if (kIsWeb) return OceanEyesReleaseTarget.web;
    return switch (defaultTargetPlatform) {
      TargetPlatform.android => OceanEyesReleaseTarget.android,
      TargetPlatform.iOS => OceanEyesReleaseTarget.ios,
      _ => OceanEyesReleaseTarget.all,
    };
  }

  Map<String, Object?> get _dartDefines => <String, Object?>{
    'OCEANEYES_PRODUCTION': enabled,
    'OCEANEYES_APP_CHECK': appCheckEnabled,
    'OCEANEYES_APP_CHECK_DEBUG': appCheckDebug,
    'OCEANEYES_FUNCTIONS_REGION': functionsRegion,
    'OCEANEYES_FIREBASE_EMULATORS': useFirebaseEmulators,
    'OCEANEYES_FIRESTORE_EMULATOR_HOST': firestoreEmulatorHost,
    'OCEANEYES_AUTH_EMULATOR_HOST': authEmulatorHost,
    'OCEANEYES_FUNCTIONS_EMULATOR_HOST': functionsEmulatorHost,
    'OCEANEYES_FIREBASE_API_KEY': apiKey,
    'OCEANEYES_FIREBASE_PROJECT_ID': projectId,
    'OCEANEYES_FIREBASE_MESSAGING_SENDER_ID': messagingSenderId,
    'OCEANEYES_FIREBASE_ANDROID_APP_ID': androidAppId,
    'OCEANEYES_FIREBASE_IOS_APP_ID': iosAppId,
    'OCEANEYES_FIREBASE_WEB_APP_ID': webAppId,
    'OCEANEYES_FIREBASE_AUTH_DOMAIN': authDomain,
    'OCEANEYES_FIREBASE_STORAGE_BUCKET': storageBucket,
    'OCEANEYES_FIREBASE_MEASUREMENT_ID': measurementId,
    'OCEANEYES_FIREBASE_IOS_BUNDLE_ID': iosBundleId,
    'OCEANEYES_FIREBASE_IOS_CLIENT_ID': iosClientId,
    'OCEANEYES_FIREBASE_ANDROID_CLIENT_ID': androidClientId,
    'OCEANEYES_GOOGLE_WEB_CLIENT_ID': googleWebClientId,
    'OCEANEYES_FIREBASE_WEB_PUSH_VAPID_KEY': webPushVapidKey,
    'OCEANEYES_RECAPTCHA_V3_SITE_KEY': recaptchaV3SiteKey,
    'OCEANEYES_BUILD_NAME': buildName,
    'OCEANEYES_BUILD_NUMBER': buildNumber,
    'OCEANEYES_PRIVACY_POLICY_URL': privacyPolicyUrl,
    'OCEANEYES_TERMS_OF_SERVICE_URL': termsOfServiceUrl,
  };

  static bool _isConfigured(String value) {
    return value.trim().isNotEmpty &&
        !OceanEyesReleaseConfigGuard.isPlaceholder(value);
  }
}
