import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';

/// Build-time production settings.
///
/// Values are deliberately supplied with `--dart-define` or
/// `--dart-define-from-file`; no environment-specific Firebase configuration
/// is committed to the repository. Native builds may instead rely on the
/// gitignored files generated by `flutterfire configure`.
class OceanEyesProductionConfig {
  const OceanEyesProductionConfig({
    required this.appCheckEnabled,
    required this.appCheckDebug,
    required this.recaptchaV3SiteKey,
    required this.functionsRegion,
    required this.useFirebaseEmulators,
    required this.firestoreEmulatorHost,
    required this.firestoreEmulatorPort,
    required this.authEmulatorHost,
    required this.authEmulatorPort,
    required this.functionsEmulatorHost,
    required this.functionsEmulatorPort,
    required this.apiKey,
    required this.projectId,
    required this.messagingSenderId,
    required this.androidAppId,
    required this.iosAppId,
    required this.webAppId,
    required this.authDomain,
    required this.storageBucket,
    required this.measurementId,
    required this.iosBundleId,
    required this.iosClientId,
    required this.androidClientId,
    required this.googleWebClientId,
    required this.webPushVapidKey,
  });

  factory OceanEyesProductionConfig.fromEnvironment() {
    return OceanEyesProductionConfig(
      appCheckEnabled: const bool.fromEnvironment(
        'OCEANEYES_APP_CHECK',
        defaultValue: true,
      ),
      appCheckDebug: const bool.fromEnvironment('OCEANEYES_APP_CHECK_DEBUG'),
      recaptchaV3SiteKey: const String.fromEnvironment(
        'OCEANEYES_RECAPTCHA_V3_SITE_KEY',
      ),
      functionsRegion: const String.fromEnvironment(
        'OCEANEYES_FUNCTIONS_REGION',
        defaultValue: 'us-central1',
      ),
      useFirebaseEmulators: const bool.fromEnvironment(
        'OCEANEYES_FIREBASE_EMULATORS',
      ),
      firestoreEmulatorHost: const String.fromEnvironment(
        'OCEANEYES_FIRESTORE_EMULATOR_HOST',
        defaultValue: 'localhost',
      ),
      firestoreEmulatorPort: const int.fromEnvironment(
        'OCEANEYES_FIRESTORE_EMULATOR_PORT',
        defaultValue: 8080,
      ),
      authEmulatorHost: const String.fromEnvironment(
        'OCEANEYES_AUTH_EMULATOR_HOST',
        defaultValue: 'localhost',
      ),
      authEmulatorPort: const int.fromEnvironment(
        'OCEANEYES_AUTH_EMULATOR_PORT',
        defaultValue: 9099,
      ),
      functionsEmulatorHost: const String.fromEnvironment(
        'OCEANEYES_FUNCTIONS_EMULATOR_HOST',
        defaultValue: 'localhost',
      ),
      functionsEmulatorPort: const int.fromEnvironment(
        'OCEANEYES_FUNCTIONS_EMULATOR_PORT',
        defaultValue: 5001,
      ),
      apiKey: const String.fromEnvironment('OCEANEYES_FIREBASE_API_KEY'),
      projectId: const String.fromEnvironment('OCEANEYES_FIREBASE_PROJECT_ID'),
      messagingSenderId: const String.fromEnvironment(
        'OCEANEYES_FIREBASE_MESSAGING_SENDER_ID',
      ),
      androidAppId: const String.fromEnvironment(
        'OCEANEYES_FIREBASE_ANDROID_APP_ID',
      ),
      iosAppId: const String.fromEnvironment('OCEANEYES_FIREBASE_IOS_APP_ID'),
      webAppId: const String.fromEnvironment('OCEANEYES_FIREBASE_WEB_APP_ID'),
      authDomain: const String.fromEnvironment(
        'OCEANEYES_FIREBASE_AUTH_DOMAIN',
      ),
      storageBucket: const String.fromEnvironment(
        'OCEANEYES_FIREBASE_STORAGE_BUCKET',
      ),
      measurementId: const String.fromEnvironment(
        'OCEANEYES_FIREBASE_MEASUREMENT_ID',
      ),
      iosBundleId: const String.fromEnvironment(
        'OCEANEYES_FIREBASE_IOS_BUNDLE_ID',
        defaultValue: 'com.oceaneyes.oceaneyes',
      ),
      iosClientId: const String.fromEnvironment(
        'OCEANEYES_FIREBASE_IOS_CLIENT_ID',
      ),
      androidClientId: const String.fromEnvironment(
        'OCEANEYES_FIREBASE_ANDROID_CLIENT_ID',
      ),
      googleWebClientId: const String.fromEnvironment(
        'OCEANEYES_GOOGLE_WEB_CLIENT_ID',
      ),
      webPushVapidKey: const String.fromEnvironment(
        'OCEANEYES_FIREBASE_WEB_PUSH_VAPID_KEY',
      ),
    );
  }

  final bool appCheckEnabled;
  final bool appCheckDebug;
  final String recaptchaV3SiteKey;
  final String functionsRegion;
  final bool useFirebaseEmulators;
  final String firestoreEmulatorHost;
  final int firestoreEmulatorPort;
  final String authEmulatorHost;
  final int authEmulatorPort;
  final String functionsEmulatorHost;
  final int functionsEmulatorPort;

  final String apiKey;
  final String projectId;
  final String messagingSenderId;
  final String androidAppId;
  final String iosAppId;
  final String webAppId;
  final String authDomain;
  final String storageBucket;
  final String measurementId;
  final String iosBundleId;
  final String iosClientId;
  final String androidClientId;
  final String googleWebClientId;
  final String webPushVapidKey;

  bool get hasDartDefinedFirebaseOptions =>
      apiKey.isNotEmpty &&
      projectId.isNotEmpty &&
      messagingSenderId.isNotEmpty &&
      _appIdForCurrentPlatform.isNotEmpty;

  /// Returns null on native platforms when setup should be loaded from the
  /// generated Google service file. Web always requires explicit options.
  FirebaseOptions? firebaseOptionsForCurrentPlatform() {
    if (!hasDartDefinedFirebaseOptions) return null;
    return FirebaseOptions(
      apiKey: apiKey,
      appId: _appIdForCurrentPlatform,
      messagingSenderId: messagingSenderId,
      projectId: projectId,
      authDomain: authDomain.isEmpty ? null : authDomain,
      storageBucket: storageBucket.isEmpty ? null : storageBucket,
      measurementId: measurementId.isEmpty ? null : measurementId,
      iosBundleId: defaultTargetPlatform == TargetPlatform.iOS
          ? iosBundleId
          : null,
      iosClientId: defaultTargetPlatform == TargetPlatform.iOS
          ? (iosClientId.isEmpty ? null : iosClientId)
          : null,
      androidClientId: defaultTargetPlatform == TargetPlatform.android
          ? (androidClientId.isEmpty ? null : androidClientId)
          : null,
    );
  }

  String get _appIdForCurrentPlatform {
    if (kIsWeb) return webAppId;
    return switch (defaultTargetPlatform) {
      TargetPlatform.android => androidAppId,
      TargetPlatform.iOS => iosAppId,
      _ => '',
    };
  }

  /// A user-facing configuration problem, or null when startup can proceed.
  String? validate() {
    if (kIsWeb && !hasDartDefinedFirebaseOptions) {
      return 'Flutter web requires OCEANEYES_FIREBASE_* dart-defines.';
    }
    if (kIsWeb && googleWebClientId.trim().isEmpty) {
      return 'Web Google linking requires OCEANEYES_GOOGLE_WEB_CLIENT_ID.';
    }
    if (kIsWeb && appCheckEnabled && recaptchaV3SiteKey.isEmpty) {
      return 'Web App Check requires OCEANEYES_RECAPTCHA_V3_SITE_KEY.';
    }
    if (functionsRegion.trim().isEmpty) {
      return 'OCEANEYES_FUNCTIONS_REGION cannot be empty.';
    }
    return null;
  }
}
