// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4ON6Qoffqhb3yNIFthNQh7s-xdtywJDE',
    appId: '1:1072877532089:web:4c99a42a94950cb72fbc68',
    messagingSenderId: '1072877532089',
    projectId: 'ocean-eyes-webapp',
    authDomain: 'ocean-eyes-webapp.firebaseapp.com',
    storageBucket: 'ocean-eyes-webapp.firebasestorage.app',
    measurementId: 'G-TS7JCHHWLG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-R0Pq7_J9j6RGsC3XRVk-hNgGJMCBXJQ',
    appId: '1:1072877532089:android:d7aac1fb54b47d8d2fbc68',
    messagingSenderId: '1072877532089',
    projectId: 'ocean-eyes-webapp',
    storageBucket: 'ocean-eyes-webapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuk_DbqCUOjc7Ik0NwxorxkyPQkML7zb4',
    appId: '1:1072877532089:ios:360237b46af319ea2fbc68',
    messagingSenderId: '1072877532089',
    projectId: 'ocean-eyes-webapp',
    storageBucket: 'ocean-eyes-webapp.firebasestorage.app',
    iosBundleId: 'com.oceaneyes.oceaneyes',
  );
}
